services:
  zobitools:
    build: .
    container_name: zobitools
    restart: always
    env_file: .env
    ports:       
      - "3000" 
    networks:
      - global

networks:
  global:
    external: true
